# Generated by Django 5.2.16 on 2026-07-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_hash', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('window_started_at', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
