# Generated by Django 5.2.16 on 2026-07-20 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('reason', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_adjustments', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='adjustment', to='wallets.ledgerentry')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='wallets.wallet')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='wallet_adjustment_nonzero')],
            },
        ),
    ]
